# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=50)),
                ('phonenumber', models.CharField(default='', max_length=11)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
